Repository sparta-igo-jo/Newsfeed-app, pull requests merged in 2025-02, with the labels that each got.

#1 Feat: User 프로필 관리 개발
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeed/global/common/exception/GlobalControllerAdvice.java
  src/main/java/com/example/newsfeed/global/response/ErrorResponse.java
  src/main/java/com/example/newsfeed/global/response/Response.java
  src/main/java/com/example/newsfeed/user/application/converter/UserConverter.java
  src/main/java/com/example/newsfeed/user/application/service/UserService.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/request/CreateUserRequestDto.java
  src/main/java/com/example/newsfeed/user/dto/request/DeleteUserRequestDto.java
  src/main/java/com/example/newsfeed/user/dto/request/UpdateUserPasswordRequestDto.java
  src/main/java/com/example/newsfeed/user/dto/request/UpdateUserRequestDto.java
  src/main/java/com/example/newsfeed/user/dto/response/GetAllUsersResponseDto.java
  src/main/java/com/example/newsfeed/user/dto/response/GetUserResponseDto.java
  src/main/java/com/example/newsfeed/user/entity/User.java
  src/main/java/com/example/newsfeed/user/exception/InvalidPasswordException.java
  src/main/java/com/example/newsfeed/user/exception/PasswordSameAsOldException.java
  src/main/java/com/example/newsfeed/user/exception/UserNotFoundException.java
  src/main/java/com/example/newsfeed/user/exception/UserUpdateFailedException.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
  src/test/java/com/example/newsfeed/user/application/service/UserServiceTest.java
Labels: enhancement

#2 Feature/feeds Feat: Feed 관리 개발
  src/main/java/com/example/newsfeed/feed/application/converter/FeedConverter.java
  src/main/java/com/example/newsfeed/feed/application/service/FeedService.java
  src/main/java/com/example/newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/newsfeed/feed/dto/request/CreateFeedRequestDto.java
  src/main/java/com/example/newsfeed/feed/dto/request/UpdateFeedRequestDto.java
  src/main/java/com/example/newsfeed/feed/dto/response/CreateFeedResponseDto.java
  src/main/java/com/example/newsfeed/feed/dto/response/GetAllFeedsResponseDto.java
  src/main/java/com/example/newsfeed/feed/dto/response/GetFeedResponseDto.java
  src/main/java/com/example/newsfeed/feed/entity/Feed.java
  src/main/java/com/example/newsfeed/feed/exception/FeedNotFoundException.java
  src/main/java/com/example/newsfeed/feed/exception/FeedUpdateFailedException.java
  src/main/java/com/example/newsfeed/feed/repository/FeedRepository.java
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
Labels: enhancement

#3 사용자 로그인 인증, 기능 개발
  src/main/java/com/example/newsfeed/auth/application/converter/AuthConverter.java
  src/main/java/com/example/newsfeed/auth/application/service/AuthService.java
  src/main/java/com/example/newsfeed/auth/controller/AuthController.java
  src/main/java/com/example/newsfeed/auth/dto/request/LoginUserRequestDto.java
  src/main/java/com/example/newsfeed/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/com/example/newsfeed/auth/dto/response/LoginUserResponseDto.java
  src/main/java/com/example/newsfeed/auth/dto/response/SignUpUserResponseDto.java
  src/main/java/com/example/newsfeed/auth/exception/UserEmailDuplicationExcepion.java
  src/main/java/com/example/newsfeed/auth/exception/UserNameDuplicationException.java
  src/main/java/com/example/newsfeed/auth/exception/UserNotLoginException.java
  src/main/java/com/example/newsfeed/auth/repository/AuthRepository.java
  src/main/java/com/example/newsfeed/global/common/Const/SessionConst.java
  src/main/java/com/example/newsfeed/global/common/Interceptor/AuthInterceptor.java
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeed/global/config/WebConfig.java
  src/test/java/com/example/newsfeed/NewsfeedApplicationTests.java
Labels: enhancement

#8 feat: 피드 수정, 삭제 시 Authorization 검증 추가
  src/main/java/com/example/newsfeed/feed/application/converter/FeedConverter.java
  src/main/java/com/example/newsfeed/feed/application/service/FeedService.java
  src/main/java/com/example/newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/newsfeed/feed/dto/response/CreateFeedResponseDto.java
  src/main/java/com/example/newsfeed/feed/repository/FeedRepository.java
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
Labels: enhancement

#10 Feat: GlobalControllerAdvice 추가
  src/main/java/com/example/newsfeed/auth/controller/AuthController.java
  src/main/java/com/example/newsfeed/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/com/example/newsfeed/global/common/Const/SessionConst.java
  src/main/java/com/example/newsfeed/global/common/constant/PasswordRegexpConst.java
  src/main/java/com/example/newsfeed/global/common/constant/SessionConst.java
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeed/global/common/exception/GlobalControllerAdvice.java
  src/main/java/com/example/newsfeed/global/common/interceptor/AuthInterceptor.java
  src/main/java/com/example/newsfeed/global/config/WebConfig.java
  src/main/java/com/example/newsfeed/global/response/DefaultResponse.java
  src/main/java/com/example/newsfeed/global/response/Response.java
  src/main/java/com/example/newsfeed/user/dto/request/UpdateUserPasswordRequestDto.java
Labels: enhancement, fix

#12 Feat: 유저 서비스에 세션을 통한 검증 추가
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeed/global/common/exception/GlobalControllerAdvice.java
  src/main/java/com/example/newsfeed/user/application/converter/UserConverter.java
  src/main/java/com/example/newsfeed/user/application/service/UserService.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/request/SearchUserRequestDto.java
  src/main/java/com/example/newsfeed/user/dto/response/GetAllUsersResponseDto.java
  src/main/java/com/example/newsfeed/user/dto/response/GetUserResponseDto.java
  src/main/java/com/example/newsfeed/user/exception/UserAccessDeniedException.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
Labels: enhancement, refactor

#14 Feat: 파일 서비스 추가
  src/main/java/com/example/newsfeed/global/common/constant/ImageUrlConst.java
  src/main/java/com/example/newsfeed/global/common/file/FileType.java
  src/main/java/com/example/newsfeed/global/common/file/controller/FileController.java
  src/main/java/com/example/newsfeed/global/common/file/exception/FileUploadFailedException.java
  src/main/java/com/example/newsfeed/global/common/file/service/FileService.java
  src/main/java/com/example/newsfeed/global/common/file/service/LocalFileService.java
  src/main/java/com/example/newsfeed/global/config/FileServiceConfig.java
  src/main/java/com/example/newsfeed/global/config/StaticResourceConfig.java
Labels: enhancement, fix

#13 Refactor: 코드 일부 수정
  src/main/java/com/example/newsfeed/comment/application/converter/CommentConverter.java
  src/main/java/com/example/newsfeed/comment/application/service/CommentService.java
  src/main/java/com/example/newsfeed/comment/controller/CommentController.java
  src/main/java/com/example/newsfeed/comment/dto/request/UpdateCommnetRequestDto.java
  src/main/java/com/example/newsfeed/comment/dto/response/GetCommentIdResponseDto.java
  src/main/java/com/example/newsfeed/comment/dto/response/GetCommentResponseDto.java
  src/main/java/com/example/newsfeed/comment/dto/response/GetCommentResponseWrapperDto.java
  src/main/java/com/example/newsfeed/comment/entity/Comment.java
  src/main/java/com/example/newsfeed/comment/exception/BaseException.java
  src/main/java/com/example/newsfeed/comment/exception/CommentNotFoundException.java
  src/main/java/com/example/newsfeed/comment/exception/ErrorCode.java
  src/main/java/com/example/newsfeed/comment/exception/ErrorDetail.java
  src/main/java/com/example/newsfeed/comment/exception/GlobalControllerAdvice.java
  src/main/java/com/example/newsfeed/comment/exception/UnauthorizedUserException.java
  src/main/java/com/example/newsfeed/feed/application/converter/FeedConverter.java
  src/main/java/com/example/newsfeed/feed/application/service/FeedService.java
  src/main/java/com/example/newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/newsfeed/feed/dto/response/GetAllFeedsResponseDto.java
  src/main/java/com/example/newsfeed/feed/dto/response/GetFeedResponseDto.java
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeed/global/config/PageableConfig.java
Labels: refactor

#15 Feat: 좋아요 기능 추가
  src/main/java/com/example/newsfeed/feed/entity/Feed.java
  src/main/java/com/example/newsfeed/follow/application/service/FollowService.java
  src/main/java/com/example/newsfeed/follow/controller/FollowController.java
  src/main/java/com/example/newsfeed/follow/entity/Follow.java
  src/main/java/com/example/newsfeed/follow/exception/CannotFollowSelfException.java
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/global/common/exception/ErrorCode.java
  src/main/java/com/example/newsfeed/like/application/service/LikeService.java
  src/main/java/com/example/newsfeed/like/controller/FollowController.java
  src/main/java/com/example/newsfeed/like/controller/LikeController.java
  src/main/java/com/example/newsfeed/like/dto/LikeResponseDto.java
  src/main/java/com/example/newsfeed/like/entity/Like.java
  src/main/java/com/example/newsfeed/like/repository/LikeRepository.java
Labels: enhancement

#16 Refactor : comment 기능 리팩토링
  src/main/java/com/example/newsfeed/auth/application/service/AuthService.java
  src/main/java/com/example/newsfeed/auth/controller/AuthController.java
  src/main/java/com/example/newsfeed/comment/application/service/CommentService.java
  src/main/java/com/example/newsfeed/comment/controller/CommentController.java
  src/main/java/com/example/newsfeed/comment/dto/request/CreateCommentRequestDto.java
  src/main/java/com/example/newsfeed/comment/dto/request/UpdateCommnetRequestDto.java
  src/main/java/com/example/newsfeed/comment/dto/response/GetCommentResponseDto.java
  src/main/java/com/example/newsfeed/comment/dto/response/UpdateCommentResponseDto.java
  src/main/java/com/example/newsfeed/comment/entity/Comment.java
  src/main/java/com/example/newsfeed/comment/repository/CommentRepository.java
  src/main/java/com/example/newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/newsfeed/global/common/interceptor/AuthInterceptor.java
Labels: refactor

#17 Feat: 피드 이미지 생성, 수정 기능 추가
  src/main/java/com/example/newsfeed/feed/application/converter/FeedConverter.java
  src/main/java/com/example/newsfeed/feed/application/service/FeedService.java
  src/main/java/com/example/newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/newsfeed/feed/dto/request/CreateFeedRequestDto.java
  src/main/java/com/example/newsfeed/feed/dto/request/UpdateFeedRequestDto.java
  src/main/java/com/example/newsfeed/feed/repository/FeedRepository.java
Labels: enhancement, refactor, fix

#18 Feat: 유저 탈퇴 시 연관된 내용 삭제 로직 추가
  src/main/java/com/example/newsfeed/follow/application/service/FollowService.java
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/global/common/constant/ImageUrlConst.java
  src/main/java/com/example/newsfeed/global/common/file/FileType.java
  src/main/java/com/example/newsfeed/global/common/file/service/LocalFileService.java
  src/main/java/com/example/newsfeed/user/application/service/UserService.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/request/UpdateUserRequestDto.java
  src/main/java/com/example/newsfeed/user/entity/User.java
Labels: enhancement, refactor

#22 Refactor: 전체 파일 리팩토링
  .gitignore
  src/main/java/com/example/newsfeed/auth/application/service/AuthService.java
  src/main/java/com/example/newsfeed/auth/controller/AuthController.java
  src/main/java/com/example/newsfeed/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/com/example/newsfeed/auth/exception/UserEmailDuplicationExcepion.java
  src/main/java/com/example/newsfeed/auth/exception/UserNameDuplicationException.java
  src/main/java/com/example/newsfeed/auth/exception/UserNotLoginException.java
  src/main/java/com/example/newsfeed/auth/repository/AuthRepository.java
  src/main/java/com/example/newsfeed/comment/application/converter/CommentConverter.java
  src/main/java/com/example/newsfeed/comment/application/service/CommentReadService.java
  src/main/java/com/example/newsfeed/comment/application/service/CommentService.java
  src/main/java/com/example/newsfeed/comment/application/service/CommentWriteService.java
  src/main/java/com/example/newsfeed/comment/controller/CommentController.java
  src/main/java/com/example/newsfeed/comment/dto/response/UpdateCommentResponseDto.java
  src/main/java/com/example/newsfeed/comment/entity/Comment.java
  src/main/java/com/example/newsfeed/comment/exception/CommentNotFoundException.java
  src/main/java/com/example/newsfeed/comment/exception/UnauthorizedUserException.java
  src/main/java/com/example/newsfeed/comment/repository/CommentRepository.java
  src/main/java/com/example/newsfeed/feed/application/service/FeedReadService.java
  src/main/java/com/example/newsfeed/feed/application/service/FeedService.java
  src/main/java/com/example/newsfeed/feed/application/service/FeedWriteService.java
  src/main/java/com/example/newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/newsfeed/feed/dto/request/CreateFeedRequestDto.java
  src/main/java/com/example/newsfeed/feed/dto/request/UpdateFeedRequestDto.java
  src/main/java/com/example/newsfeed/feed/entity/Feed.java
  src/main/java/com/example/newsfeed/feed/exception/FeedNotFoundException.java
  src/main/java/com/example/newsfeed/feed/exception/FeedUpdateFailedException.java
  src/main/java/com/example/newsfeed/feed/repository/FeedRepository.java
  src/main/java/com/example/newsfeed/follow/application/service/FollowReadService.java
  src/main/java/com/example/newsfeed/follow/application/service/FollowService.java
  src/main/java/com/example/newsfeed/follow/application/service/FollowWriteService.java
  src/main/java/com/example/newsfeed/follow/controller/FollowController.java
  src/main/java/com/example/newsfeed/follow/entity/Follow.java
  src/main/java/com/example/newsfeed/follow/exception/CannotFollowSelfException.java
  src/main/java/com/example/newsfeed/global/common/constant/PasswordRegexpConst.java
  src/main/java/com/example/newsfeed/global/common/constant/RegexpConst.java
  src/main/java/com/example/newsfeed/global/common/exception/GlobalControllerAdvice.java
  src/main/java/com/example/newsfeed/global/common/file/service/LocalFileService.java
  src/main/java/com/example/newsfeed/global/common/interceptor/AuthInterceptor.java
  src/main/java/com/example/newsfeed/global/config/FileServiceConfig.java
  src/main/java/com/example/newsfeed/global/config/WebConfig.java
  src/main/java/com/example/newsfeed/like/application/service/LikeService.java
  src/main/java/com/example/newsfeed/like/application/service/LikeWriteService.java
  src/main/java/com/example/newsfeed/like/controller/LikeController.java
  src/main/java/com/example/newsfeed/like/entity/Like.java
  src/main/java/com/example/newsfeed/like/repository/LikeRepository.java
  src/main/java/com/example/newsfeed/user/application/service/UserReadService.java
  src/main/java/com/example/newsfeed/user/application/service/UserWriteService.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/request/UpdateUserPasswordRequestDto.java
  src/main/java/com/example/newsfeed/user/exception/InvalidPasswordException.java
  src/main/java/com/example/newsfeed/user/exception/PasswordSameAsOldException.java
  src/main/java/com/example/newsfeed/user/exception/UserAccessDeniedException.java
  src/main/java/com/example/newsfeed/user/exception/UserNotFoundException.java
  src/main/java/com/example/newsfeed/user/exception/UserUpdateFailedException.java
  src/test/java/com/example/newsfeed/user/application/service/UserServiceTest.java
Labels: refactor, fix

#23 Feat: 유저 목록조회 기능 추가
  src/main/java/com/example/newsfeed/user/application/service/UserReadService.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/request/GetUsersRequestDto.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
Labels: enhancement

#25 Feat: FollowReadService 메서드 추가
  src/main/java/com/example/newsfeed/follow/application/converter/FollowConverter.java
  src/main/java/com/example/newsfeed/follow/application/service/FollowReadService.java
  src/main/java/com/example/newsfeed/follow/controller/FollowController.java
  src/main/java/com/example/newsfeed/follow/dto/response/GetFollowResponseDto.java
  src/main/java/com/example/newsfeed/follow/entity/Follow.java
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/like/entity/Like.java
  src/main/java/com/example/newsfeed/user/application/service/UserReadService.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/request/SearchUserRequestDto.java
Labels: enhancement, refactor

#26 Docs: README.md 추가
  README.md
Labels: documentation

#30 Fix: 테스트 진행 결과가 예상과 다르거나 문제가 있던 부분 수정
  src/main/java/com/example/newsfeed/comment/application/service/CommentReadService.java
  src/main/java/com/example/newsfeed/comment/application/service/CommentWriteService.java
  src/main/java/com/example/newsfeed/comment/controller/CommentController.java
  src/main/java/com/example/newsfeed/global/common/exception/GlobalControllerAdvice.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
Labels: fix

#27 Chore: 데이터베이스 초기화를 위한 `schema.sql` 추가
  src/main/java/com/example/newsfeed/follow/entity/Follow.java
  src/main/java/com/example/newsfeed/like/entity/Like.java
  src/main/resources/application.yml
  src/main/resources/prod/application-datasource.yml
  src/main/resources/schema.sql
Labels: documentation
